### ISSUE TITLE
 android.permission.INTERACT_ACROSS_USERS_FULL

### ISSUE THREAD

**Issue by coderscoding** [oda-alexandre/msf-persistance-android#3]
When i am execurting the script : 

Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] pkg=–-user }
java.lang.SecurityException: Permission Denial: startActivity asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
        at android.os.Parcel.readException(Parcel.java:1692)
        at android.os.Parcel.readException(Parcel.java:1645)
        at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:3152)
        at com.android.commands.am.Am.runStart(Am.java:643)
        at com.android.commands.am.Am.onRun(Am.java:394)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:124)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:352)

How Can i fix it? 
OS :  Android 7.1.2

**Comment by Obligado1** [comment]
Also finding solution to this problem, I guess the persistence don't work anymore

**Comment by coderscoding** [comment]
Ya I also think Android is improving day by day itself :) than that just 2 year before.
